name: CI
on: [push, pull_request]

jobs:
  # Ensure correct Rust code formatting
  formatting:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2023-08-24
          components: rustfmt
      - name: Format check
        run: |
          cargo fmt --all -- --check

  # Build plugin
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Build
        run: |
          cargo build --release --verbose --target x86_64-pc-windows-msvc 
      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: r2rcon-rs-${{ steps.extract.outputs.commit }}
          path: |
            target/release/*.dll
            target/release/*.pdb
